# Generated by Django 5.2 on 2025-07-31 17:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="UserProfile",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "avatar",
                    models.ImageField(
                        blank=True,
                        help_text="用户头像图片",
                        null=True,
                        upload_to="avatars/%Y/%m/",
                        verbose_name="头像",
                    ),
                ),
                (
                    "timezone",
                    models.CharField(
                        default="Asia/Shanghai",
                        help_text="用户所在时区",
                        max_length=50,
                        verbose_name="时区",
                    ),
                ),
                (
                    "task_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="用户创建的任务总数量",
                        verbose_name="任务总数",
                    ),
                ),
                (
                    "completed_task_count",
                    models.PositiveIntegerField(
                        default=0,
                        help_text="用户已完成的任务数量",
                        verbose_name="已完成任务数",
                    ),
                ),
                (
                    "theme_preference",
                    models.CharField(
                        choices=[
                            ("light", "浅色主题"),
                            ("dark", "深色主题"),
                            ("auto", "跟随系统"),
                        ],
                        default="auto",
                        help_text="用户界面主题偏好",
                        max_length=20,
                        verbose_name="主题偏好",
                    ),
                ),
                (
                    "email_notifications",
                    models.BooleanField(
                        default=True,
                        help_text="是否接收邮件通知",
                        verbose_name="邮件通知",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "user",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="profile",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="关联用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "用户扩展信息",
                "verbose_name_plural": "用户扩展信息",
                "db_table": "user_profiles",
                "ordering": ["-created_at"],
            },
        ),
    ]
