# Generated by Django 5.2 on 2025-07-31 17:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LingTaskFlow", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="LoginHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "username_attempted",
                    models.CharField(
                        help_text="记录登录尝试时使用的用户名或邮箱",
                        max_length=150,
                        verbose_name="尝试的用户名",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("success", "成功"),
                            ("failed", "失败"),
                            ("locked", "账户锁定"),
                        ],
                        max_length=10,
                        verbose_name="登录状态",
                    ),
                ),
                (
                    "ip_address",
                    models.GenericIPAddressField(
                        help_text="用户登录时的IP地址", verbose_name="IP地址"
                    ),
                ),
                (
                    "user_agent",
                    models.TextField(
                        help_text="浏览器和设备信息", verbose_name="用户代理"
                    ),
                ),
                (
                    "device_fingerprint",
                    models.CharField(
                        blank=True,
                        help_text="基于多个因素生成的设备唯一标识",
                        max_length=64,
                        null=True,
                        verbose_name="设备指纹",
                    ),
                ),
                (
                    "location",
                    models.CharField(
                        blank=True,
                        help_text="基于IP地址的大致地理位置",
                        max_length=255,
                        null=True,
                        verbose_name="地理位置",
                    ),
                ),
                (
                    "login_time",
                    models.DateTimeField(auto_now_add=True, verbose_name="登录时间"),
                ),
                (
                    "session_duration",
                    models.DurationField(
                        blank=True,
                        help_text="从登录到登出的时间长度",
                        null=True,
                        verbose_name="会话持续时间",
                    ),
                ),
                (
                    "failure_reason",
                    models.CharField(
                        blank=True,
                        help_text="登录失败时的具体原因",
                        max_length=255,
                        null=True,
                        verbose_name="失败原因",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="login_history",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="用户",
                    ),
                ),
            ],
            options={
                "verbose_name": "登录历史",
                "verbose_name_plural": "登录历史记录",
                "ordering": ["-login_time"],
                "indexes": [
                    models.Index(
                        fields=["user", "-login_time"],
                        name="LingTaskFlo_user_id_42fb66_idx",
                    ),
                    models.Index(
                        fields=["ip_address", "-login_time"],
                        name="LingTaskFlo_ip_addr_8c39fb_idx",
                    ),
                    models.Index(
                        fields=["status", "-login_time"],
                        name="LingTaskFlo_status_cec4b8_idx",
                    ),
                ],
            },
        ),
    ]
