# Generated by Django 5.2.4 on 2025-08-01 12:13

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LingTaskFlow", "0002_loginhistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="Task",
            fields=[
                (
                    "is_deleted",
                    models.BooleanField(
                        default=False,
                        help_text="软删除标记，True表示已删除",
                        verbose_name="是否删除",
                    ),
                ),
                (
                    "deleted_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="记录删除时间",
                        null=True,
                        verbose_name="删除时间",
                    ),
                ),
                (
                    "id",
                    models.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                        verbose_name="任务ID",
                    ),
                ),
                (
                    "title",
                    models.CharField(
                        help_text="任务的简短描述",
                        max_length=200,
                        verbose_name="任务标题",
                    ),
                ),
                (
                    "description",
                    models.TextField(
                        blank=True, help_text="任务的详细说明", verbose_name="任务描述"
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "待处理"),
                            ("IN_PROGRESS", "进行中"),
                            ("COMPLETED", "已完成"),
                            ("CANCELLED", "已取消"),
                            ("ON_HOLD", "暂停"),
                        ],
                        default="PENDING",
                        max_length=20,
                        verbose_name="任务状态",
                    ),
                ),
                (
                    "priority",
                    models.CharField(
                        choices=[
                            ("LOW", "低"),
                            ("MEDIUM", "中"),
                            ("HIGH", "高"),
                            ("URGENT", "紧急"),
                        ],
                        default="MEDIUM",
                        max_length=10,
                        verbose_name="优先级",
                    ),
                ),
                (
                    "due_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="任务需要完成的时间",
                        null=True,
                        verbose_name="截止时间",
                    ),
                ),
                (
                    "start_date",
                    models.DateTimeField(
                        blank=True,
                        help_text="任务计划开始的时间",
                        null=True,
                        verbose_name="开始时间",
                    ),
                ),
                (
                    "completed_at",
                    models.DateTimeField(
                        blank=True,
                        help_text="任务实际完成的时间",
                        null=True,
                        verbose_name="完成时间",
                    ),
                ),
                (
                    "progress",
                    models.IntegerField(
                        default=0,
                        help_text="任务完成百分比 (0-100)",
                        validators=[
                            django.core.validators.MinValueValidator(0),
                            django.core.validators.MaxValueValidator(100),
                        ],
                        verbose_name="完成进度",
                    ),
                ),
                (
                    "estimated_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="预计完成任务需要的小时数",
                        max_digits=8,
                        null=True,
                        verbose_name="预估工时",
                    ),
                ),
                (
                    "actual_hours",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        help_text="实际花费的小时数",
                        max_digits=8,
                        null=True,
                        verbose_name="实际工时",
                    ),
                ),
                (
                    "category",
                    models.CharField(
                        blank=True,
                        help_text="任务所属的分类",
                        max_length=50,
                        verbose_name="任务分类",
                    ),
                ),
                (
                    "tags",
                    models.CharField(
                        blank=True,
                        help_text="用逗号分隔的标签列表",
                        max_length=255,
                        verbose_name="标签",
                    ),
                ),
                (
                    "attachment",
                    models.FileField(
                        blank=True,
                        help_text="任务相关的文件附件",
                        null=True,
                        upload_to="task_attachments/%Y/%m/",
                        verbose_name="附件",
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="任务的额外备注信息", verbose_name="备注"
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="创建时间"),
                ),
                (
                    "updated_at",
                    models.DateTimeField(auto_now=True, verbose_name="更新时间"),
                ),
                (
                    "order",
                    models.IntegerField(
                        default=0, help_text="用于任务排序的数值", verbose_name="排序"
                    ),
                ),
                (
                    "assigned_to",
                    models.ForeignKey(
                        blank=True,
                        help_text="分配给谁执行这个任务",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="任务执行者",
                    ),
                ),
                (
                    "owner",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="owned_tasks",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="任务所有者",
                    ),
                ),
            ],
            options={
                "verbose_name": "任务",
                "verbose_name_plural": "任务",
                "db_table": "tasks",
                "ordering": ["-created_at", "order"],
                "indexes": [
                    models.Index(
                        fields=["owner", "-created_at"], name="tasks_owner_i_7197c8_idx"
                    ),
                    models.Index(
                        fields=["assigned_to", "-created_at"],
                        name="tasks_assigne_49fa0c_idx",
                    ),
                    models.Index(
                        fields=["status", "priority"], name="tasks_status_0fbdac_idx"
                    ),
                    models.Index(fields=["due_date"], name="tasks_due_dat_0359a9_idx"),
                    models.Index(
                        fields=["is_deleted", "-created_at"],
                        name="tasks_is_dele_403643_idx",
                    ),
                    models.Index(fields=["category"], name="tasks_categor_aecfa3_idx"),
                ],
            },
        ),
    ]
