# Generated by Django 5.2.4 on 2025-08-01 12:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("LingTaskFlow", "0003_task"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="loginhistory",
            new_name="login_user_time_idx",
            old_name="LingTaskFlo_user_id_42fb66_idx",
        ),
        migrations.RenameIndex(
            model_name="loginhistory",
            new_name="login_ip_time_idx",
            old_name="LingTaskFlo_ip_addr_8c39fb_idx",
        ),
        migrations.RenameIndex(
            model_name="loginhistory",
            new_name="login_status_time_idx",
            old_name="LingTaskFlo_status_cec4b8_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="task_due_date_idx",
            old_name="tasks_due_dat_0359a9_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="task_category_idx",
            old_name="tasks_categor_aecfa3_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="task_owner_created_idx",
            old_name="tasks_owner_i_7197c8_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="task_assign_created_idx",
            old_name="tasks_assigne_49fa0c_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="task_del_created_idx",
            old_name="tasks_is_dele_403643_idx",
        ),
        migrations.RenameIndex(
            model_name="task",
            new_name="task_status_priority_idx",
            old_name="tasks_status_0fbdac_idx",
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["username_attempted"], name="login_username_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(fields=["device_fingerprint"], name="login_device_idx"),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(fields=["location"], name="login_location_idx"),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["user", "status", "-login_time"], name="login_usr_stat_time_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["ip_address", "status"], name="login_ip_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["status", "failure_reason"], name="login_stat_reason_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(
                fields=["-login_time", "status"], name="login_time_stat_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="loginhistory",
            index=models.Index(fields=["session_duration"], name="login_session_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["status"], name="task_status_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["priority"], name="task_priority_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["order"], name="task_order_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["owner", "status", "-created_at"], name="task_own_stat_crt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "status", "-created_at"],
                name="task_asn_stat_crt_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["is_deleted", "owner", "-created_at"],
                name="task_del_own_crt_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["is_deleted", "assigned_to", "-created_at"],
                name="task_del_asn_crt_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["priority", "status", "due_date"], name="task_pri_stat_due_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["due_date", "status"], name="task_due_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["start_date", "due_date"], name="task_start_due_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["completed_at"], name="task_completed_at_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["category", "status"], name="task_cat_status_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["category", "priority"], name="task_cat_priority_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["owner", "status", "is_deleted"], name="task_own_stat_del_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["assigned_to", "status", "is_deleted"],
                name="task_asn_stat_del_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["due_date", "status", "is_deleted"],
                name="task_due_stat_del_idx",
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(fields=["-updated_at"], name="task_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                fields=["owner", "-updated_at"], name="task_owner_updated_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["user"], name="userprof_user_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["-created_at"], name="userprof_created_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["-updated_at"], name="userprof_updated_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["task_count"], name="userprof_task_cnt_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["completed_task_count"], name="userprof_comp_cnt_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(fields=["theme_preference"], name="userprof_theme_idx"),
        ),
        migrations.AddIndex(
            model_name="userprofile",
            index=models.Index(
                fields=["email_notifications"], name="userprof_email_idx"
            ),
        ),
    ]
