# Generated by Django 5.2.4 on 2025-08-01 12:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LingTaskFlow", "0004_optimize_database_indexes"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="deleted_by",
            field=models.ForeignKey(
                blank=True,
                help_text="执行删除操作的用户",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="%(class)s_deleted_set",
                to=settings.AUTH_USER_MODEL,
                verbose_name="删除者",
            ),
        ),
    ]
