# Generated by Django 5.2.4 on 2025-08-07 20:58

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LingTaskFlow", "0005_add_deleted_by_field"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="bio",
            field=models.TextField(
                blank=True,
                help_text="用户个人简介描述",
                max_length=500,
                null=True,
                verbose_name="个人简介",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="language",
            field=models.CharField(
                choices=[("zh-CN", "简体中文"), ("en-US", "English")],
                default="zh-CN",
                help_text="用户界面语言偏好",
                max_length=10,
                verbose_name="语言偏好",
            ),
        ),
        migrations.AddField(
            model_name="userprofile",
            name="phone",
            field=models.CharField(
                blank=True,
                help_text="用户联系电话",
                max_length=20,
                null=True,
                verbose_name="联系电话",
            ),
        ),
    ]
