# Generated by Django 5.2.4 on 2025-08-08 00:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LingTaskFlow", "0006_userprofile_bio_userprofile_language_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="userprofile",
            name="nickname",
            field=models.CharField(
                default="新用户",
                help_text="用户在系统中显示的昵称",
                max_length=50,
                verbose_name="昵称",
            ),
        ),
    ]
