# Generated by Django 5.2.4 on 2025-08-11 18:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("LingTaskFlow", "0007_userprofile_nickname"),
    ]

    operations = [
        migrations.AddField(
            model_name="task",
            name="overdue_count",
            field=models.PositiveIntegerField(
                default=0, help_text="任务因逾期而被限制操作的次数", verbose_name="逾期次数"
            ),
        ),
    ]
